### ISSUE TITLE
Build guide in this wiki is not reproducable

### ISSUE THREAD

**Issue by Nictheboy** [cupid-development/android_device_xiaomi_sm8450-common#7]
Thank you a lot for your work which makes it possible for me to use lineageos on my marble. That's amazing, and the binary works well on my phone.

However, when I tried to compile the source on my own according to https://lineage-wiki.mainlining.org/devices/marble/build/variant3/, it does not work.

On https://lineage-wiki.mainlining.org/devices/marble/build/variant3/, it says ```breakfast marble``` will fetch files necessary to build marble. However, since this is an unofficial support, and ```breakfast``` fetches files from LineageOS's official GitHub organization, it fails as if marble is not and never supported.

I tried to clone the necessary repos, and tried for a lot of time and the build process never succeed, and finally realized that this is very very hard, and it is not even necessary, since someone must have a manifest.xml or something similar to build lineage for marble easily, and my marble running lineage is the perfect proof for that.

I noticed that https://lineage-wiki.mainlining.org/devices/marble/build/variant3/ has a link to https://github.com/cupid-development/android_device_xiaomi_marble, and finally I found this repo which is the repo for that wiki website. And very very fortunately, I found that this project is still active till now. So I think maybe the best way to build it is to ask your support.

So, can you give me some idea on how to do the things ```breakfast marble``` does in order to get the files to build for marble?

By the way, your wiki has links to LineageOS's official IRC channel. People there criticized me for asking support for an unsupported device. Maybe you can replace these IRC channels with your own contacts.

Very very very grateful for you work that makes me possible to use LineageOS on marble, by the way!

**Comment by Nictheboy** [comment]
discovered that this is not the repo for that wiki, the right place is https://github.com/cupid-development/lineage_wiki. but since i cannot post issue on that repo, i still have to post it here. sorry for that

**Comment by ArianK16a** [comment]
That's expected and a won't fix, sorry for the trouble.
You will need to add local manifests on your own, breakfast will only work once the devices are forked to the LineageOS organisation successfully.
You can find our manifests and the required repopicks from gerrit here: https://xdaforums.com/t/development-of-lineageos-and-oss-kernel-for-xiaomi-sm-gen-4-5-10-devices.4589247/

We won't put an effort to add that into wiki since the devices are intended to get official builds eventually anyway.
Though if you really care, you could make a pull request which adds a link to the xda thread as a warning in the wiki repo.

**Comment by Nictheboy** [comment]
Thanks
